[theme]
base = "dark"
backgroundColor = "#0f0a1e"
secondaryBackgroundColor = "#2a1555"
textColor = "#FFFFFF"
primaryColor = "#9333EA"
font = "sans serif"

[server]
headless = true
port = 8501
address = "127.0.0.1"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
